### ISSUE TITLE
Falha Helper->fileToBase64

### ISSUE THREAD

**Issue by FelipeAugusto26** [wppconnect-team/wppconnect-php-client#3]
Visto a falha:

Warning: finfo_file(): Failed identify data 0:(null) in php
 quando usado para converter a imagem para envio de media
 
 Solução encontrada: 
 Function exemplo:
 /**
     * HELPER CONVERT FILE BASE64
     * @return string
     */
    public function **fileToBase64**(string $file): **string**
    {
        $type = **image_type_to_mime_type**(**exif_imagetype**($file));
        return 'data:' . $type . ';base64,' . base64_encode(file_get_contents($file));
    }
    
    Usando a função image_type_to_mime_type
    
    Abraço!!

**Comment by bgastaldi** [comment]
Fixed.
Thank you.
